title: Quotes
description: A component component render a set of testimonials with Tailwind CSS styling.

elements:
  title:
    alignment: ""

properties:
  alignment:
    type: string
    default: left
    enum:
      - left
      - center
      - right
    description: The alignment position of the testimonials carousel.

items:
  separator: section
  category: NONE
  elements:
    title:
      alignment: ''
      description: The title of the testimonial.
    tagline:
        description: The position title of the person who gave the testimonial.
    text:
      description: The text of the testimonial.
    media:
      type: image
      description: The avatar of person who gave the testimonial.
