title: Details
description: A component component designed to render FAQs elements with Tailwind CSS styling.

elements:
  background:

properties:
  title:
    type: string
    default: Frequently asked questions
    description: The title of the FAQ section.

items:
  separator: divider
  elements:
    title:
      alignment: ""
      description: The question title.
    text:
      description: The answer text.
